services:
    caddy-cloudflare:
        image: ghcr.io/nyukeit/caddy-cloudflare:latest
        container_name: caddy-cloudflare
        environment:
            - ${CLOUDFLARE_API_TOKEN}=your-long-token
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./Caddyfile:/etc/caddy/Caddyfile
            - ./data:/data
            - ./config:/config
        restart: unless-stopped
